apiVersion: skaffold/v4beta3
kind: Config
build:
  artifacts:
    - image: kashiish19/auth
      context: auth
      docker:
        dockerfile: Dockerfile
    - image: kashiish19/client
      context: client
      docker:
        dockerfile: Dockerfile
    - image: kashiish19/orders
      context: orders
      docker:
        dockerfile: Dockerfile
    - image: kashiish19/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
    - image: kashiish19/payments
      context: payments
      docker:
        dockerfile: Dockerfile
    - image: kashiish19/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
